image: Visual Studio 2017

build:
  verbosity: minimal
  publish_nuget: false

skip_commits:
  files:
  - .gitattributes
  - .gitignore
  - README.md
  - CHANGELOG.md
  - LICENSE

skip_tags: false

test: off

init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
    }

before_build:
- c:\Windows\System32\sc.exe config NetTcpPortSharing start= demand

on_finish:
- c:\Windows\System32\sc.exe config NetTcpPortSharing start= disabled
- ps: >-
    $wc = New-Object System.Net.WebClient

    $testBinPath = "bin\Release\net45"

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "src\Castle.Windsor.Tests\$testBinPath\TestResult_Windsor.xml"))

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path "src\Castle.Facilities.WcfIntegration.Tests\$testBinPath\TestResult_WcfIntegration.xml"))

    Push-AppveyorArtifact $env:APPVEYOR_BUILD_FOLDER\src\Castle.Windsor.Tests\$testBinPath\TestResult_Windsor.xml

    Push-AppveyorArtifact $env:APPVEYOR_BUILD_FOLDER\src\Castle.Facilities.WcfIntegration.Tests\$testBinPath\TestResult_WcfIntegration.xml

on_success:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        nuget push ".\build\Castle.Windsor.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.LoggingFacility.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.EventWiringFacility.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.FactorySupportFacility.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.WcfIntegrationFacility.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
        nuget push ".\build\Castle.SynchronizeFacility.${env:APPVEYOR_REPO_TAG_NAME}.nupkg" -ApiKey $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
    }

build_script:  
  - cmd: build.cmd

artifacts:
 - path: build\*.nupkg
