pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

build:
  verbosity: minimal
  publish_nuget: false

skip_commits:
  files:
  - .gitattributes
  - .gitignore
  - README.md
  - CHANGELOG.md
  - LICENSE

skip_tags: true

test: off

before_build:
  - c:\Windows\System32\sc.exe config NetTcpPortSharing start= demand

after_build:
  - c:\Windows\System32\sc.exe config NetTcpPortSharing start= disabled	

build_script:  
  - cmd: build-vs2017.cmd

